# Makefile.in generated by automake 1.11.3 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002,
# 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011 Free Software
# Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.




pkgdatadir = $(datadir)/pofswitch
pkgincludedir = $(includedir)/pofswitch
pkglibdir = $(libdir)/pofswitch
pkglibexecdir = $(libexecdir)/pofswitch
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
bin_PROGRAMS = pofswitch$(EXEEXT) pofsctrl$(EXEEXT)
DIST_COMMON = README $(am__configure_deps) $(srcdir)/Makefile.am \
	$(srcdir)/Makefile.in $(srcdir)/common/automake.mk \
	$(srcdir)/datapath/automake.mk $(srcdir)/include/automake.mk \
	$(srcdir)/local_resource/automake.mk \
	$(srcdir)/switch_control/automake.mk $(top_srcdir)/configure \
	NEWS depcomp install-sh missing
subdir = .
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/configure.in
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_CLEAN_FILES =
CONFIG_CLEAN_VPATH_FILES =
am__installdirs = "$(DESTDIR)$(bindir)"
PROGRAMS = $(bin_PROGRAMS)
am_pofsctrl_OBJECTS = pof_log_print.$(OBJEXT) \
	pof_byte_transfer.$(OBJEXT) pof_sctrl.$(OBJEXT)
pofsctrl_OBJECTS = $(am_pofsctrl_OBJECTS)
pofsctrl_LDADD = $(LDADD)
am_pofswitch_OBJECTS = pof_basefunc.$(OBJEXT) \
	pof_byte_transfer.$(OBJEXT) pof_command.$(OBJEXT) \
	pof_hmap.$(OBJEXT) pof_tree.$(OBJEXT) pof_list.$(OBJEXT) \
	pof_memory.$(OBJEXT) pof_log_print.$(OBJEXT) \
	pof_action.$(OBJEXT) pof_datapath.$(OBJEXT) \
	pof_instruction.$(OBJEXT) pof_counter.$(OBJEXT) \
	pof_flow_table.$(OBJEXT) pof_group.$(OBJEXT) \
	pof_local_resource.$(OBJEXT) pof_meter.$(OBJEXT) \
	pof_ins_block.$(OBJEXT) pof_port.$(OBJEXT) \
	pof_config.$(OBJEXT) pof_encap.$(OBJEXT) pof_parse.$(OBJEXT) \
	pof_switch_listen.$(OBJEXT) pof_switch.$(OBJEXT)
pofswitch_OBJECTS = $(am_pofswitch_OBJECTS)
pofswitch_LDADD = $(LDADD)
DEFAULT_INCLUDES = -I.
depcomp = $(SHELL) $(top_srcdir)/depcomp
am__depfiles_maybe = depfiles
am__mv = mv -f
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
CCLD = $(CC)
LINK = $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -o $@
SOURCES = $(pofsctrl_SOURCES) $(pofswitch_SOURCES)
DIST_SOURCES = $(pofsctrl_SOURCES) $(pofswitch_SOURCES)
ETAGS = etags
CTAGS = ctags
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  if test -d "$(distdir)"; then \
    find "$(distdir)" -type d ! -perm -200 -exec chmod u+w {} ';' \
      && rm -rf "$(distdir)" \
      || { sleep 5 && rm -rf "$(distdir)"; }; \
  else :; fi
DIST_ARCHIVES = $(distdir).tar.gz
GZIP_ENV = --best
distuninstallcheck_listfiles = find . -type f -print
am__distuninstallcheck_listfiles = $(distuninstallcheck_listfiles) \
  | sed 's|^\./|$(prefix)/|' | grep -v '$(infodir)/dir$$'
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} /home/shengrulee/POFSwitch/missing --run aclocal-1.11
AMTAR = $${TAR-tar}
AUTOCONF = ${SHELL} /home/shengrulee/POFSwitch/missing --run autoconf
AUTOHEADER = ${SHELL} /home/shengrulee/POFSwitch/missing --run autoheader
AUTOMAKE = ${SHELL} /home/shengrulee/POFSwitch/missing --run automake-1.11
AWK = mawk
CC = gcc
CCDEPMODE = depmode=gcc3
CFLAGS = -g -O2
CPP = gcc -E
CPPFLAGS = 
CYGPATH_W = echo
DEFS = -DPACKAGE_NAME=\"pofswitch\" -DPACKAGE_TARNAME=\"pofswitch\" -DPACKAGE_VERSION=\"1.4.0.015\" -DPACKAGE_STRING=\"pofswitch\ 1.4.0.015\" -DPACKAGE_BUGREPORT=\"yujingzhou@huawei.com\" -DPACKAGE_URL=\"\" -DPACKAGE=\"pofswitch\" -DVERSION=\"1.4.0.015\" -DPOFSWITCH_VERSION_NO=POFSwitch_VERSION_1_4_0 -DPOFSWITCH_VERSION_SUB=\"015\" -DHAVE_LIBPTHREAD=1 -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_ARPA_INET_H=1 -DHAVE_LIMITS_H=1 -DHAVE_NETINET_IN_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_SYS_SOCKET_H=1 -DHAVE_SYS_TIME_H=1 -DHAVE_UNISTD_H=1 -DHAVE_STDDEF_H=1 -DHAVE_STDBOOL_H=1 -DHAVE_ENDIAN_H=1 -DHAVE_STDLIB_H=1 -DHAVE_MALLOC=1 -DHAVE_INET_NTOA=1 -DHAVE_MEMSET=1 -DHAVE_SOCKET=1
DEPDIR = .deps
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = /bin/grep -E
EXEEXT = 
GREP = /bin/grep
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LDFLAGS = 
LIBOBJS = 
LIBS = -lpthread 
LTLIBOBJS = 
MAKEINFO = ${SHELL} /home/shengrulee/POFSwitch/missing --run makeinfo
MKDIR_P = /bin/mkdir -p
OBJEXT = o
PACKAGE = pofswitch
PACKAGE_BUGREPORT = yujingzhou@huawei.com
PACKAGE_NAME = pofswitch
PACKAGE_STRING = pofswitch 1.4.0.015
PACKAGE_TARNAME = pofswitch
PACKAGE_URL = 
PACKAGE_VERSION = 1.4.0.015
PATH_SEPARATOR = :
RANLIB = ranlib
SET_MAKE = 
SHELL = /bin/bash
STRIP = 
VERSION = 1.4.0.015
abs_builddir = /home/shengrulee/POFSwitch
abs_srcdir = /home/shengrulee/POFSwitch
abs_top_builddir = /home/shengrulee/POFSwitch
abs_top_srcdir = /home/shengrulee/POFSwitch
ac_ct_CC = gcc
am__include = include
am__leading_dot = .
am__quote = 
am__tar = $${TAR-tar} chof - "$$tardir"
am__untar = $${TAR-tar} xf -
bindir = ${exec_prefix}/bin
build_alias = clean
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host_alias = clean
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /home/shengrulee/POFSwitch/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = /bin/mkdir -p
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target_alias = clean
top_build_prefix = 
top_builddir = .
top_srcdir = .
AUTOMAKE_OPTIONS = foreign 
pofswitch_SOURCES = $(COMMON_FOLDER)/pof_basefunc.c \
	$(COMMON_FOLDER)/pof_byte_transfer.c \
	$(COMMON_FOLDER)/pof_command.c $(COMMON_FOLDER)/pof_hmap.c \
	$(COMMON_FOLDER)/pof_tree.c $(COMMON_FOLDER)/pof_list.c \
	$(COMMON_FOLDER)/pof_memory.c $(COMMON_FOLDER)/pof_log_print.c \
	$(DATAPATH_FOLDER)/pof_action.c \
	$(DATAPATH_FOLDER)/pof_datapath.c \
	$(DATAPATH_FOLDER)/pof_instruction.c \
	$(LOCAL_RESOURCE_FOLDER)/pof_counter.c \
	$(LOCAL_RESOURCE_FOLDER)/pof_flow_table.c \
	$(LOCAL_RESOURCE_FOLDER)/pof_group.c \
	$(LOCAL_RESOURCE_FOLDER)/pof_local_resource.c \
	$(LOCAL_RESOURCE_FOLDER)/pof_meter.c \
	$(LOCAL_RESOURCE_FOLDER)/pof_ins_block.c \
	$(LOCAL_RESOURCE_FOLDER)/pof_port.c \
	$(SWITCH_CONTROL_FOLDER)/pof_config.c \
	$(SWITCH_CONTROL_FOLDER)/pof_encap.c \
	$(SWITCH_CONTROL_FOLDER)/pof_parse.c \
	$(SWITCH_CONTROL_FOLDER)/pof_switch_listen.c \
	$(SWITCH_CONTROL_FOLDER)/pof_switch.c
pofsctrl_SOURCES = $(COMMON_FOLDER)/pof_log_print.c \
	$(COMMON_FOLDER)/pof_byte_transfer.c \
	$(SWITCH_CONTROL_FOLDER)/pof_sctrl.c
POFCONFIG_FILE = pofswitch_config.conf
INSTALL_DATA_PATH = /etc/pofswitch
LOG_FILE_PATH = /usr/local/var/log
SBIN_PATH = /sbin
INCLUDES = -I $(top_srcdir)/include
EXTRA_DIST = pofswitch_config.conf include/pof_byte_transfer.h \
	include/pof_command.h include/pof_common.h include/pof_conn.h \
	include/pof_datapath.h include/pof_global.h \
	include/pof_protocol_header.h include/pof_local_resource.h \
	include/pof_log_print.h include/pof_hmap.h include/pof_tree.h \
	include/pof_list.h include/pof_memory.h \
	include/pof_protocol_header.h include/pof_switch_listen.h \
	include/pof_type.h
COMMON_FOLDER = common
DATAPATH_FOLDER = datapath
LOCAL_RESOURCE_FOLDER = local_resource
SWITCH_CONTROL_FOLDER = switch_control
all: all-am

.SUFFIXES:
.SUFFIXES: .c .o .obj
am--refresh: Makefile
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am $(srcdir)/common/automake.mk $(srcdir)/datapath/automake.mk $(srcdir)/local_resource/automake.mk $(srcdir)/switch_control/automake.mk $(srcdir)/include/automake.mk $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --foreign'; \
	      $(am__cd) $(srcdir) && $(AUTOMAKE) --foreign \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --foreign Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --foreign Makefile
.PRECIOUS: Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe);; \
	esac;
$(srcdir)/common/automake.mk $(srcdir)/datapath/automake.mk $(srcdir)/local_resource/automake.mk $(srcdir)/switch_control/automake.mk $(srcdir)/include/automake.mk:

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	$(am__cd) $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	$(am__cd) $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)
$(am__aclocal_m4_deps):
install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	test -z "$(bindir)" || $(MKDIR_P) "$(DESTDIR)$(bindir)"
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	for p in $$list; do echo "$$p $$p"; done | \
	sed 's/$(EXEEXT)$$//' | \
	while read p p1; do if test -f $$p; \
	  then echo "$$p"; echo "$$p"; else :; fi; \
	done | \
	sed -e 'p;s,.*/,,;n;h' -e 's|.*|.|' \
	    -e 'p;x;s,.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/' | \
	sed 'N;N;N;s,\n, ,g' | \
	$(AWK) 'BEGIN { files["."] = ""; dirs["."] = 1 } \
	  { d=$$3; if (dirs[d] != 1) { print "d", d; dirs[d] = 1 } \
	    if ($$2 == $$4) files[d] = files[d] " " $$1; \
	    else { print "f", $$3 "/" $$4, $$1; } } \
	  END { for (d in files) print "f", d, files[d] }' | \
	while read type dir files; do \
	    if test "$$dir" = .; then dir=; else dir=/$$dir; fi; \
	    test -z "$$files" || { \
	      echo " $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$files '$(DESTDIR)$(bindir)$$dir'"; \
	      $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$files "$(DESTDIR)$(bindir)$$dir" || exit $$?; \
	    } \
	; done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	files=`for p in $$list; do echo "$$p"; done | \
	  sed -e 'h;s,^.*/,,;s/$(EXEEXT)$$//;$(transform)' \
	      -e 's/$$/$(EXEEXT)/' `; \
	test -n "$$list" || exit 0; \
	echo " ( cd '$(DESTDIR)$(bindir)' && rm -f" $$files ")"; \
	cd "$(DESTDIR)$(bindir)" && rm -f $$files

clean-binPROGRAMS:
	-test -z "$(bin_PROGRAMS)" || rm -f $(bin_PROGRAMS)
pofsctrl$(EXEEXT): $(pofsctrl_OBJECTS) $(pofsctrl_DEPENDENCIES) $(EXTRA_pofsctrl_DEPENDENCIES) 
	@rm -f pofsctrl$(EXEEXT)
	$(LINK) $(pofsctrl_OBJECTS) $(pofsctrl_LDADD) $(LIBS)
pofswitch$(EXEEXT): $(pofswitch_OBJECTS) $(pofswitch_DEPENDENCIES) $(EXTRA_pofswitch_DEPENDENCIES) 
	@rm -f pofswitch$(EXEEXT)
	$(LINK) $(pofswitch_OBJECTS) $(pofswitch_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include ./$(DEPDIR)/pof_action.Po
include ./$(DEPDIR)/pof_basefunc.Po
include ./$(DEPDIR)/pof_byte_transfer.Po
include ./$(DEPDIR)/pof_command.Po
include ./$(DEPDIR)/pof_config.Po
include ./$(DEPDIR)/pof_counter.Po
include ./$(DEPDIR)/pof_datapath.Po
include ./$(DEPDIR)/pof_encap.Po
include ./$(DEPDIR)/pof_flow_table.Po
include ./$(DEPDIR)/pof_group.Po
include ./$(DEPDIR)/pof_hmap.Po
include ./$(DEPDIR)/pof_ins_block.Po
include ./$(DEPDIR)/pof_instruction.Po
include ./$(DEPDIR)/pof_list.Po
include ./$(DEPDIR)/pof_local_resource.Po
include ./$(DEPDIR)/pof_log_print.Po
include ./$(DEPDIR)/pof_memory.Po
include ./$(DEPDIR)/pof_meter.Po
include ./$(DEPDIR)/pof_parse.Po
include ./$(DEPDIR)/pof_port.Po
include ./$(DEPDIR)/pof_sctrl.Po
include ./$(DEPDIR)/pof_switch.Po
include ./$(DEPDIR)/pof_switch_listen.Po
include ./$(DEPDIR)/pof_tree.Po

.c.o:
	$(COMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ $<
	$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(COMPILE) -c $<

.c.obj:
	$(COMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ `$(CYGPATH_W) '$<'`
	$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(COMPILE) -c `$(CYGPATH_W) '$<'`

pof_log_print.o: $(COMMON_FOLDER)/pof_log_print.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT pof_log_print.o -MD -MP -MF $(DEPDIR)/pof_log_print.Tpo -c -o pof_log_print.o `test -f '$(COMMON_FOLDER)/pof_log_print.c' || echo '$(srcdir)/'`$(COMMON_FOLDER)/pof_log_print.c
	$(am__mv) $(DEPDIR)/pof_log_print.Tpo $(DEPDIR)/pof_log_print.Po
#	source='$(COMMON_FOLDER)/pof_log_print.c' object='pof_log_print.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o pof_log_print.o `test -f '$(COMMON_FOLDER)/pof_log_print.c' || echo '$(srcdir)/'`$(COMMON_FOLDER)/pof_log_print.c

pof_log_print.obj: $(COMMON_FOLDER)/pof_log_print.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT pof_log_print.obj -MD -MP -MF $(DEPDIR)/pof_log_print.Tpo -c -o pof_log_print.obj `if test -f '$(COMMON_FOLDER)/pof_log_print.c'; then $(CYGPATH_W) '$(COMMON_FOLDER)/pof_log_print.c'; else $(CYGPATH_W) '$(srcdir)/$(COMMON_FOLDER)/pof_log_print.c'; fi`
	$(am__mv) $(DEPDIR)/pof_log_print.Tpo $(DEPDIR)/pof_log_print.Po
#	source='$(COMMON_FOLDER)/pof_log_print.c' object='pof_log_print.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o pof_log_print.obj `if test -f '$(COMMON_FOLDER)/pof_log_print.c'; then $(CYGPATH_W) '$(COMMON_FOLDER)/pof_log_print.c'; else $(CYGPATH_W) '$(srcdir)/$(COMMON_FOLDER)/pof_log_print.c'; fi`

pof_byte_transfer.o: $(COMMON_FOLDER)/pof_byte_transfer.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT pof_byte_transfer.o -MD -MP -MF $(DEPDIR)/pof_byte_transfer.Tpo -c -o pof_byte_transfer.o `test -f '$(COMMON_FOLDER)/pof_byte_transfer.c' || echo '$(srcdir)/'`$(COMMON_FOLDER)/pof_byte_transfer.c
	$(am__mv) $(DEPDIR)/pof_byte_transfer.Tpo $(DEPDIR)/pof_byte_transfer.Po
#	source='$(COMMON_FOLDER)/pof_byte_transfer.c' object='pof_byte_transfer.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o pof_byte_transfer.o `test -f '$(COMMON_FOLDER)/pof_byte_transfer.c' || echo '$(srcdir)/'`$(COMMON_FOLDER)/pof_byte_transfer.c

pof_byte_transfer.obj: $(COMMON_FOLDER)/pof_byte_transfer.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT pof_byte_transfer.obj -MD -MP -MF $(DEPDIR)/pof_byte_transfer.Tpo -c -o pof_byte_transfer.obj `if test -f '$(COMMON_FOLDER)/pof_byte_transfer.c'; then $(CYGPATH_W) '$(COMMON_FOLDER)/pof_byte_transfer.c'; else $(CYGPATH_W) '$(srcdir)/$(COMMON_FOLDER)/pof_byte_transfer.c'; fi`
	$(am__mv) $(DEPDIR)/pof_byte_transfer.Tpo $(DEPDIR)/pof_byte_transfer.Po
#	source='$(COMMON_FOLDER)/pof_byte_transfer.c' object='pof_byte_transfer.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o pof_byte_transfer.obj `if test -f '$(COMMON_FOLDER)/pof_byte_transfer.c'; then $(CYGPATH_W) '$(COMMON_FOLDER)/pof_byte_transfer.c'; else $(CYGPATH_W) '$(srcdir)/$(COMMON_FOLDER)/pof_byte_transfer.c'; fi`

pof_sctrl.o: $(SWITCH_CONTROL_FOLDER)/pof_sctrl.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT pof_sctrl.o -MD -MP -MF $(DEPDIR)/pof_sctrl.Tpo -c -o pof_sctrl.o `test -f '$(SWITCH_CONTROL_FOLDER)/pof_sctrl.c' || echo '$(srcdir)/'`$(SWITCH_CONTROL_FOLDER)/pof_sctrl.c
	$(am__mv) $(DEPDIR)/pof_sctrl.Tpo $(DEPDIR)/pof_sctrl.Po
#	source='$(SWITCH_CONTROL_FOLDER)/pof_sctrl.c' object='pof_sctrl.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o pof_sctrl.o `test -f '$(SWITCH_CONTROL_FOLDER)/pof_sctrl.c' || echo '$(srcdir)/'`$(SWITCH_CONTROL_FOLDER)/pof_sctrl.c

pof_sctrl.obj: $(SWITCH_CONTROL_FOLDER)/pof_sctrl.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT pof_sctrl.obj -MD -MP -MF $(DEPDIR)/pof_sctrl.Tpo -c -o pof_sctrl.obj `if test -f '$(SWITCH_CONTROL_FOLDER)/pof_sctrl.c'; then $(CYGPATH_W) '$(SWITCH_CONTROL_FOLDER)/pof_sctrl.c'; else $(CYGPATH_W) '$(srcdir)/$(SWITCH_CONTROL_FOLDER)/pof_sctrl.c'; fi`
	$(am__mv) $(DEPDIR)/pof_sctrl.Tpo $(DEPDIR)/pof_sctrl.Po
#	source='$(SWITCH_CONTROL_FOLDER)/pof_sctrl.c' object='pof_sctrl.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o pof_sctrl.obj `if test -f '$(SWITCH_CONTROL_FOLDER)/pof_sctrl.c'; then $(CYGPATH_W) '$(SWITCH_CONTROL_FOLDER)/pof_sctrl.c'; else $(CYGPATH_W) '$(srcdir)/$(SWITCH_CONTROL_FOLDER)/pof_sctrl.c'; fi`

pof_basefunc.o: $(COMMON_FOLDER)/pof_basefunc.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT pof_basefunc.o -MD -MP -MF $(DEPDIR)/pof_basefunc.Tpo -c -o pof_basefunc.o `test -f '$(COMMON_FOLDER)/pof_basefunc.c' || echo '$(srcdir)/'`$(COMMON_FOLDER)/pof_basefunc.c
	$(am__mv) $(DEPDIR)/pof_basefunc.Tpo $(DEPDIR)/pof_basefunc.Po
#	source='$(COMMON_FOLDER)/pof_basefunc.c' object='pof_basefunc.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o pof_basefunc.o `test -f '$(COMMON_FOLDER)/pof_basefunc.c' || echo '$(srcdir)/'`$(COMMON_FOLDER)/pof_basefunc.c

pof_basefunc.obj: $(COMMON_FOLDER)/pof_basefunc.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT pof_basefunc.obj -MD -MP -MF $(DEPDIR)/pof_basefunc.Tpo -c -o pof_basefunc.obj `if test -f '$(COMMON_FOLDER)/pof_basefunc.c'; then $(CYGPATH_W) '$(COMMON_FOLDER)/pof_basefunc.c'; else $(CYGPATH_W) '$(srcdir)/$(COMMON_FOLDER)/pof_basefunc.c'; fi`
	$(am__mv) $(DEPDIR)/pof_basefunc.Tpo $(DEPDIR)/pof_basefunc.Po
#	source='$(COMMON_FOLDER)/pof_basefunc.c' object='pof_basefunc.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o pof_basefunc.obj `if test -f '$(COMMON_FOLDER)/pof_basefunc.c'; then $(CYGPATH_W) '$(COMMON_FOLDER)/pof_basefunc.c'; else $(CYGPATH_W) '$(srcdir)/$(COMMON_FOLDER)/pof_basefunc.c'; fi`

pof_command.o: $(COMMON_FOLDER)/pof_command.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT pof_command.o -MD -MP -MF $(DEPDIR)/pof_command.Tpo -c -o pof_command.o `test -f '$(COMMON_FOLDER)/pof_command.c' || echo '$(srcdir)/'`$(COMMON_FOLDER)/pof_command.c
	$(am__mv) $(DEPDIR)/pof_command.Tpo $(DEPDIR)/pof_command.Po
#	source='$(COMMON_FOLDER)/pof_command.c' object='pof_command.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o pof_command.o `test -f '$(COMMON_FOLDER)/pof_command.c' || echo '$(srcdir)/'`$(COMMON_FOLDER)/pof_command.c

pof_command.obj: $(COMMON_FOLDER)/pof_command.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT pof_command.obj -MD -MP -MF $(DEPDIR)/pof_command.Tpo -c -o pof_command.obj `if test -f '$(COMMON_FOLDER)/pof_command.c'; then $(CYGPATH_W) '$(COMMON_FOLDER)/pof_command.c'; else $(CYGPATH_W) '$(srcdir)/$(COMMON_FOLDER)/pof_command.c'; fi`
	$(am__mv) $(DEPDIR)/pof_command.Tpo $(DEPDIR)/pof_command.Po
#	source='$(COMMON_FOLDER)/pof_command.c' object='pof_command.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o pof_command.obj `if test -f '$(COMMON_FOLDER)/pof_command.c'; then $(CYGPATH_W) '$(COMMON_FOLDER)/pof_command.c'; else $(CYGPATH_W) '$(srcdir)/$(COMMON_FOLDER)/pof_command.c'; fi`

pof_hmap.o: $(COMMON_FOLDER)/pof_hmap.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT pof_hmap.o -MD -MP -MF $(DEPDIR)/pof_hmap.Tpo -c -o pof_hmap.o `test -f '$(COMMON_FOLDER)/pof_hmap.c' || echo '$(srcdir)/'`$(COMMON_FOLDER)/pof_hmap.c
	$(am__mv) $(DEPDIR)/pof_hmap.Tpo $(DEPDIR)/pof_hmap.Po
#	source='$(COMMON_FOLDER)/pof_hmap.c' object='pof_hmap.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o pof_hmap.o `test -f '$(COMMON_FOLDER)/pof_hmap.c' || echo '$(srcdir)/'`$(COMMON_FOLDER)/pof_hmap.c

pof_hmap.obj: $(COMMON_FOLDER)/pof_hmap.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT pof_hmap.obj -MD -MP -MF $(DEPDIR)/pof_hmap.Tpo -c -o pof_hmap.obj `if test -f '$(COMMON_FOLDER)/pof_hmap.c'; then $(CYGPATH_W) '$(COMMON_FOLDER)/pof_hmap.c'; else $(CYGPATH_W) '$(srcdir)/$(COMMON_FOLDER)/pof_hmap.c'; fi`
	$(am__mv) $(DEPDIR)/pof_hmap.Tpo $(DEPDIR)/pof_hmap.Po
#	source='$(COMMON_FOLDER)/pof_hmap.c' object='pof_hmap.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o pof_hmap.obj `if test -f '$(COMMON_FOLDER)/pof_hmap.c'; then $(CYGPATH_W) '$(COMMON_FOLDER)/pof_hmap.c'; else $(CYGPATH_W) '$(srcdir)/$(COMMON_FOLDER)/pof_hmap.c'; fi`

pof_tree.o: $(COMMON_FOLDER)/pof_tree.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT pof_tree.o -MD -MP -MF $(DEPDIR)/pof_tree.Tpo -c -o pof_tree.o `test -f '$(COMMON_FOLDER)/pof_tree.c' || echo '$(srcdir)/'`$(COMMON_FOLDER)/pof_tree.c
	$(am__mv) $(DEPDIR)/pof_tree.Tpo $(DEPDIR)/pof_tree.Po
#	source='$(COMMON_FOLDER)/pof_tree.c' object='pof_tree.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o pof_tree.o `test -f '$(COMMON_FOLDER)/pof_tree.c' || echo '$(srcdir)/'`$(COMMON_FOLDER)/pof_tree.c

pof_tree.obj: $(COMMON_FOLDER)/pof_tree.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT pof_tree.obj -MD -MP -MF $(DEPDIR)/pof_tree.Tpo -c -o pof_tree.obj `if test -f '$(COMMON_FOLDER)/pof_tree.c'; then $(CYGPATH_W) '$(COMMON_FOLDER)/pof_tree.c'; else $(CYGPATH_W) '$(srcdir)/$(COMMON_FOLDER)/pof_tree.c'; fi`
	$(am__mv) $(DEPDIR)/pof_tree.Tpo $(DEPDIR)/pof_tree.Po
#	source='$(COMMON_FOLDER)/pof_tree.c' object='pof_tree.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o pof_tree.obj `if test -f '$(COMMON_FOLDER)/pof_tree.c'; then $(CYGPATH_W) '$(COMMON_FOLDER)/pof_tree.c'; else $(CYGPATH_W) '$(srcdir)/$(COMMON_FOLDER)/pof_tree.c'; fi`

pof_list.o: $(COMMON_FOLDER)/pof_list.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT pof_list.o -MD -MP -MF $(DEPDIR)/pof_list.Tpo -c -o pof_list.o `test -f '$(COMMON_FOLDER)/pof_list.c' || echo '$(srcdir)/'`$(COMMON_FOLDER)/pof_list.c
	$(am__mv) $(DEPDIR)/pof_list.Tpo $(DEPDIR)/pof_list.Po
#	source='$(COMMON_FOLDER)/pof_list.c' object='pof_list.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o pof_list.o `test -f '$(COMMON_FOLDER)/pof_list.c' || echo '$(srcdir)/'`$(COMMON_FOLDER)/pof_list.c

pof_list.obj: $(COMMON_FOLDER)/pof_list.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT pof_list.obj -MD -MP -MF $(DEPDIR)/pof_list.Tpo -c -o pof_list.obj `if test -f '$(COMMON_FOLDER)/pof_list.c'; then $(CYGPATH_W) '$(COMMON_FOLDER)/pof_list.c'; else $(CYGPATH_W) '$(srcdir)/$(COMMON_FOLDER)/pof_list.c'; fi`
	$(am__mv) $(DEPDIR)/pof_list.Tpo $(DEPDIR)/pof_list.Po
#	source='$(COMMON_FOLDER)/pof_list.c' object='pof_list.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o pof_list.obj `if test -f '$(COMMON_FOLDER)/pof_list.c'; then $(CYGPATH_W) '$(COMMON_FOLDER)/pof_list.c'; else $(CYGPATH_W) '$(srcdir)/$(COMMON_FOLDER)/pof_list.c'; fi`

pof_memory.o: $(COMMON_FOLDER)/pof_memory.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT pof_memory.o -MD -MP -MF $(DEPDIR)/pof_memory.Tpo -c -o pof_memory.o `test -f '$(COMMON_FOLDER)/pof_memory.c' || echo '$(srcdir)/'`$(COMMON_FOLDER)/pof_memory.c
	$(am__mv) $(DEPDIR)/pof_memory.Tpo $(DEPDIR)/pof_memory.Po
#	source='$(COMMON_FOLDER)/pof_memory.c' object='pof_memory.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o pof_memory.o `test -f '$(COMMON_FOLDER)/pof_memory.c' || echo '$(srcdir)/'`$(COMMON_FOLDER)/pof_memory.c

pof_memory.obj: $(COMMON_FOLDER)/pof_memory.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT pof_memory.obj -MD -MP -MF $(DEPDIR)/pof_memory.Tpo -c -o pof_memory.obj `if test -f '$(COMMON_FOLDER)/pof_memory.c'; then $(CYGPATH_W) '$(COMMON_FOLDER)/pof_memory.c'; else $(CYGPATH_W) '$(srcdir)/$(COMMON_FOLDER)/pof_memory.c'; fi`
	$(am__mv) $(DEPDIR)/pof_memory.Tpo $(DEPDIR)/pof_memory.Po
#	source='$(COMMON_FOLDER)/pof_memory.c' object='pof_memory.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o pof_memory.obj `if test -f '$(COMMON_FOLDER)/pof_memory.c'; then $(CYGPATH_W) '$(COMMON_FOLDER)/pof_memory.c'; else $(CYGPATH_W) '$(srcdir)/$(COMMON_FOLDER)/pof_memory.c'; fi`

pof_action.o: $(DATAPATH_FOLDER)/pof_action.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT pof_action.o -MD -MP -MF $(DEPDIR)/pof_action.Tpo -c -o pof_action.o `test -f '$(DATAPATH_FOLDER)/pof_action.c' || echo '$(srcdir)/'`$(DATAPATH_FOLDER)/pof_action.c
	$(am__mv) $(DEPDIR)/pof_action.Tpo $(DEPDIR)/pof_action.Po
#	source='$(DATAPATH_FOLDER)/pof_action.c' object='pof_action.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o pof_action.o `test -f '$(DATAPATH_FOLDER)/pof_action.c' || echo '$(srcdir)/'`$(DATAPATH_FOLDER)/pof_action.c

pof_action.obj: $(DATAPATH_FOLDER)/pof_action.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT pof_action.obj -MD -MP -MF $(DEPDIR)/pof_action.Tpo -c -o pof_action.obj `if test -f '$(DATAPATH_FOLDER)/pof_action.c'; then $(CYGPATH_W) '$(DATAPATH_FOLDER)/pof_action.c'; else $(CYGPATH_W) '$(srcdir)/$(DATAPATH_FOLDER)/pof_action.c'; fi`
	$(am__mv) $(DEPDIR)/pof_action.Tpo $(DEPDIR)/pof_action.Po
#	source='$(DATAPATH_FOLDER)/pof_action.c' object='pof_action.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o pof_action.obj `if test -f '$(DATAPATH_FOLDER)/pof_action.c'; then $(CYGPATH_W) '$(DATAPATH_FOLDER)/pof_action.c'; else $(CYGPATH_W) '$(srcdir)/$(DATAPATH_FOLDER)/pof_action.c'; fi`

pof_datapath.o: $(DATAPATH_FOLDER)/pof_datapath.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT pof_datapath.o -MD -MP -MF $(DEPDIR)/pof_datapath.Tpo -c -o pof_datapath.o `test -f '$(DATAPATH_FOLDER)/pof_datapath.c' || echo '$(srcdir)/'`$(DATAPATH_FOLDER)/pof_datapath.c
	$(am__mv) $(DEPDIR)/pof_datapath.Tpo $(DEPDIR)/pof_datapath.Po
#	source='$(DATAPATH_FOLDER)/pof_datapath.c' object='pof_datapath.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o pof_datapath.o `test -f '$(DATAPATH_FOLDER)/pof_datapath.c' || echo '$(srcdir)/'`$(DATAPATH_FOLDER)/pof_datapath.c

pof_datapath.obj: $(DATAPATH_FOLDER)/pof_datapath.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT pof_datapath.obj -MD -MP -MF $(DEPDIR)/pof_datapath.Tpo -c -o pof_datapath.obj `if test -f '$(DATAPATH_FOLDER)/pof_datapath.c'; then $(CYGPATH_W) '$(DATAPATH_FOLDER)/pof_datapath.c'; else $(CYGPATH_W) '$(srcdir)/$(DATAPATH_FOLDER)/pof_datapath.c'; fi`
	$(am__mv) $(DEPDIR)/pof_datapath.Tpo $(DEPDIR)/pof_datapath.Po
#	source='$(DATAPATH_FOLDER)/pof_datapath.c' object='pof_datapath.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o pof_datapath.obj `if test -f '$(DATAPATH_FOLDER)/pof_datapath.c'; then $(CYGPATH_W) '$(DATAPATH_FOLDER)/pof_datapath.c'; else $(CYGPATH_W) '$(srcdir)/$(DATAPATH_FOLDER)/pof_datapath.c'; fi`

pof_instruction.o: $(DATAPATH_FOLDER)/pof_instruction.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT pof_instruction.o -MD -MP -MF $(DEPDIR)/pof_instruction.Tpo -c -o pof_instruction.o `test -f '$(DATAPATH_FOLDER)/pof_instruction.c' || echo '$(srcdir)/'`$(DATAPATH_FOLDER)/pof_instruction.c
	$(am__mv) $(DEPDIR)/pof_instruction.Tpo $(DEPDIR)/pof_instruction.Po
#	source='$(DATAPATH_FOLDER)/pof_instruction.c' object='pof_instruction.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o pof_instruction.o `test -f '$(DATAPATH_FOLDER)/pof_instruction.c' || echo '$(srcdir)/'`$(DATAPATH_FOLDER)/pof_instruction.c

pof_instruction.obj: $(DATAPATH_FOLDER)/pof_instruction.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT pof_instruction.obj -MD -MP -MF $(DEPDIR)/pof_instruction.Tpo -c -o pof_instruction.obj `if test -f '$(DATAPATH_FOLDER)/pof_instruction.c'; then $(CYGPATH_W) '$(DATAPATH_FOLDER)/pof_instruction.c'; else $(CYGPATH_W) '$(srcdir)/$(DATAPATH_FOLDER)/pof_instruction.c'; fi`
	$(am__mv) $(DEPDIR)/pof_instruction.Tpo $(DEPDIR)/pof_instruction.Po
#	source='$(DATAPATH_FOLDER)/pof_instruction.c' object='pof_instruction.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o pof_instruction.obj `if test -f '$(DATAPATH_FOLDER)/pof_instruction.c'; then $(CYGPATH_W) '$(DATAPATH_FOLDER)/pof_instruction.c'; else $(CYGPATH_W) '$(srcdir)/$(DATAPATH_FOLDER)/pof_instruction.c'; fi`

pof_counter.o: $(LOCAL_RESOURCE_FOLDER)/pof_counter.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT pof_counter.o -MD -MP -MF $(DEPDIR)/pof_counter.Tpo -c -o pof_counter.o `test -f '$(LOCAL_RESOURCE_FOLDER)/pof_counter.c' || echo '$(srcdir)/'`$(LOCAL_RESOURCE_FOLDER)/pof_counter.c
	$(am__mv) $(DEPDIR)/pof_counter.Tpo $(DEPDIR)/pof_counter.Po
#	source='$(LOCAL_RESOURCE_FOLDER)/pof_counter.c' object='pof_counter.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o pof_counter.o `test -f '$(LOCAL_RESOURCE_FOLDER)/pof_counter.c' || echo '$(srcdir)/'`$(LOCAL_RESOURCE_FOLDER)/pof_counter.c

pof_counter.obj: $(LOCAL_RESOURCE_FOLDER)/pof_counter.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT pof_counter.obj -MD -MP -MF $(DEPDIR)/pof_counter.Tpo -c -o pof_counter.obj `if test -f '$(LOCAL_RESOURCE_FOLDER)/pof_counter.c'; then $(CYGPATH_W) '$(LOCAL_RESOURCE_FOLDER)/pof_counter.c'; else $(CYGPATH_W) '$(srcdir)/$(LOCAL_RESOURCE_FOLDER)/pof_counter.c'; fi`
	$(am__mv) $(DEPDIR)/pof_counter.Tpo $(DEPDIR)/pof_counter.Po
#	source='$(LOCAL_RESOURCE_FOLDER)/pof_counter.c' object='pof_counter.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o pof_counter.obj `if test -f '$(LOCAL_RESOURCE_FOLDER)/pof_counter.c'; then $(CYGPATH_W) '$(LOCAL_RESOURCE_FOLDER)/pof_counter.c'; else $(CYGPATH_W) '$(srcdir)/$(LOCAL_RESOURCE_FOLDER)/pof_counter.c'; fi`

pof_flow_table.o: $(LOCAL_RESOURCE_FOLDER)/pof_flow_table.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT pof_flow_table.o -MD -MP -MF $(DEPDIR)/pof_flow_table.Tpo -c -o pof_flow_table.o `test -f '$(LOCAL_RESOURCE_FOLDER)/pof_flow_table.c' || echo '$(srcdir)/'`$(LOCAL_RESOURCE_FOLDER)/pof_flow_table.c
	$(am__mv) $(DEPDIR)/pof_flow_table.Tpo $(DEPDIR)/pof_flow_table.Po
#	source='$(LOCAL_RESOURCE_FOLDER)/pof_flow_table.c' object='pof_flow_table.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o pof_flow_table.o `test -f '$(LOCAL_RESOURCE_FOLDER)/pof_flow_table.c' || echo '$(srcdir)/'`$(LOCAL_RESOURCE_FOLDER)/pof_flow_table.c

pof_flow_table.obj: $(LOCAL_RESOURCE_FOLDER)/pof_flow_table.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT pof_flow_table.obj -MD -MP -MF $(DEPDIR)/pof_flow_table.Tpo -c -o pof_flow_table.obj `if test -f '$(LOCAL_RESOURCE_FOLDER)/pof_flow_table.c'; then $(CYGPATH_W) '$(LOCAL_RESOURCE_FOLDER)/pof_flow_table.c'; else $(CYGPATH_W) '$(srcdir)/$(LOCAL_RESOURCE_FOLDER)/pof_flow_table.c'; fi`
	$(am__mv) $(DEPDIR)/pof_flow_table.Tpo $(DEPDIR)/pof_flow_table.Po
#	source='$(LOCAL_RESOURCE_FOLDER)/pof_flow_table.c' object='pof_flow_table.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o pof_flow_table.obj `if test -f '$(LOCAL_RESOURCE_FOLDER)/pof_flow_table.c'; then $(CYGPATH_W) '$(LOCAL_RESOURCE_FOLDER)/pof_flow_table.c'; else $(CYGPATH_W) '$(srcdir)/$(LOCAL_RESOURCE_FOLDER)/pof_flow_table.c'; fi`

pof_group.o: $(LOCAL_RESOURCE_FOLDER)/pof_group.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT pof_group.o -MD -MP -MF $(DEPDIR)/pof_group.Tpo -c -o pof_group.o `test -f '$(LOCAL_RESOURCE_FOLDER)/pof_group.c' || echo '$(srcdir)/'`$(LOCAL_RESOURCE_FOLDER)/pof_group.c
	$(am__mv) $(DEPDIR)/pof_group.Tpo $(DEPDIR)/pof_group.Po
#	source='$(LOCAL_RESOURCE_FOLDER)/pof_group.c' object='pof_group.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o pof_group.o `test -f '$(LOCAL_RESOURCE_FOLDER)/pof_group.c' || echo '$(srcdir)/'`$(LOCAL_RESOURCE_FOLDER)/pof_group.c

pof_group.obj: $(LOCAL_RESOURCE_FOLDER)/pof_group.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT pof_group.obj -MD -MP -MF $(DEPDIR)/pof_group.Tpo -c -o pof_group.obj `if test -f '$(LOCAL_RESOURCE_FOLDER)/pof_group.c'; then $(CYGPATH_W) '$(LOCAL_RESOURCE_FOLDER)/pof_group.c'; else $(CYGPATH_W) '$(srcdir)/$(LOCAL_RESOURCE_FOLDER)/pof_group.c'; fi`
	$(am__mv) $(DEPDIR)/pof_group.Tpo $(DEPDIR)/pof_group.Po
#	source='$(LOCAL_RESOURCE_FOLDER)/pof_group.c' object='pof_group.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o pof_group.obj `if test -f '$(LOCAL_RESOURCE_FOLDER)/pof_group.c'; then $(CYGPATH_W) '$(LOCAL_RESOURCE_FOLDER)/pof_group.c'; else $(CYGPATH_W) '$(srcdir)/$(LOCAL_RESOURCE_FOLDER)/pof_group.c'; fi`

pof_local_resource.o: $(LOCAL_RESOURCE_FOLDER)/pof_local_resource.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT pof_local_resource.o -MD -MP -MF $(DEPDIR)/pof_local_resource.Tpo -c -o pof_local_resource.o `test -f '$(LOCAL_RESOURCE_FOLDER)/pof_local_resource.c' || echo '$(srcdir)/'`$(LOCAL_RESOURCE_FOLDER)/pof_local_resource.c
	$(am__mv) $(DEPDIR)/pof_local_resource.Tpo $(DEPDIR)/pof_local_resource.Po
#	source='$(LOCAL_RESOURCE_FOLDER)/pof_local_resource.c' object='pof_local_resource.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o pof_local_resource.o `test -f '$(LOCAL_RESOURCE_FOLDER)/pof_local_resource.c' || echo '$(srcdir)/'`$(LOCAL_RESOURCE_FOLDER)/pof_local_resource.c

pof_local_resource.obj: $(LOCAL_RESOURCE_FOLDER)/pof_local_resource.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT pof_local_resource.obj -MD -MP -MF $(DEPDIR)/pof_local_resource.Tpo -c -o pof_local_resource.obj `if test -f '$(LOCAL_RESOURCE_FOLDER)/pof_local_resource.c'; then $(CYGPATH_W) '$(LOCAL_RESOURCE_FOLDER)/pof_local_resource.c'; else $(CYGPATH_W) '$(srcdir)/$(LOCAL_RESOURCE_FOLDER)/pof_local_resource.c'; fi`
	$(am__mv) $(DEPDIR)/pof_local_resource.Tpo $(DEPDIR)/pof_local_resource.Po
#	source='$(LOCAL_RESOURCE_FOLDER)/pof_local_resource.c' object='pof_local_resource.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o pof_local_resource.obj `if test -f '$(LOCAL_RESOURCE_FOLDER)/pof_local_resource.c'; then $(CYGPATH_W) '$(LOCAL_RESOURCE_FOLDER)/pof_local_resource.c'; else $(CYGPATH_W) '$(srcdir)/$(LOCAL_RESOURCE_FOLDER)/pof_local_resource.c'; fi`

pof_meter.o: $(LOCAL_RESOURCE_FOLDER)/pof_meter.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT pof_meter.o -MD -MP -MF $(DEPDIR)/pof_meter.Tpo -c -o pof_meter.o `test -f '$(LOCAL_RESOURCE_FOLDER)/pof_meter.c' || echo '$(srcdir)/'`$(LOCAL_RESOURCE_FOLDER)/pof_meter.c
	$(am__mv) $(DEPDIR)/pof_meter.Tpo $(DEPDIR)/pof_meter.Po
#	source='$(LOCAL_RESOURCE_FOLDER)/pof_meter.c' object='pof_meter.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o pof_meter.o `test -f '$(LOCAL_RESOURCE_FOLDER)/pof_meter.c' || echo '$(srcdir)/'`$(LOCAL_RESOURCE_FOLDER)/pof_meter.c

pof_meter.obj: $(LOCAL_RESOURCE_FOLDER)/pof_meter.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT pof_meter.obj -MD -MP -MF $(DEPDIR)/pof_meter.Tpo -c -o pof_meter.obj `if test -f '$(LOCAL_RESOURCE_FOLDER)/pof_meter.c'; then $(CYGPATH_W) '$(LOCAL_RESOURCE_FOLDER)/pof_meter.c'; else $(CYGPATH_W) '$(srcdir)/$(LOCAL_RESOURCE_FOLDER)/pof_meter.c'; fi`
	$(am__mv) $(DEPDIR)/pof_meter.Tpo $(DEPDIR)/pof_meter.Po
#	source='$(LOCAL_RESOURCE_FOLDER)/pof_meter.c' object='pof_meter.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o pof_meter.obj `if test -f '$(LOCAL_RESOURCE_FOLDER)/pof_meter.c'; then $(CYGPATH_W) '$(LOCAL_RESOURCE_FOLDER)/pof_meter.c'; else $(CYGPATH_W) '$(srcdir)/$(LOCAL_RESOURCE_FOLDER)/pof_meter.c'; fi`

pof_ins_block.o: $(LOCAL_RESOURCE_FOLDER)/pof_ins_block.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT pof_ins_block.o -MD -MP -MF $(DEPDIR)/pof_ins_block.Tpo -c -o pof_ins_block.o `test -f '$(LOCAL_RESOURCE_FOLDER)/pof_ins_block.c' || echo '$(srcdir)/'`$(LOCAL_RESOURCE_FOLDER)/pof_ins_block.c
	$(am__mv) $(DEPDIR)/pof_ins_block.Tpo $(DEPDIR)/pof_ins_block.Po
#	source='$(LOCAL_RESOURCE_FOLDER)/pof_ins_block.c' object='pof_ins_block.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o pof_ins_block.o `test -f '$(LOCAL_RESOURCE_FOLDER)/pof_ins_block.c' || echo '$(srcdir)/'`$(LOCAL_RESOURCE_FOLDER)/pof_ins_block.c

pof_ins_block.obj: $(LOCAL_RESOURCE_FOLDER)/pof_ins_block.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT pof_ins_block.obj -MD -MP -MF $(DEPDIR)/pof_ins_block.Tpo -c -o pof_ins_block.obj `if test -f '$(LOCAL_RESOURCE_FOLDER)/pof_ins_block.c'; then $(CYGPATH_W) '$(LOCAL_RESOURCE_FOLDER)/pof_ins_block.c'; else $(CYGPATH_W) '$(srcdir)/$(LOCAL_RESOURCE_FOLDER)/pof_ins_block.c'; fi`
	$(am__mv) $(DEPDIR)/pof_ins_block.Tpo $(DEPDIR)/pof_ins_block.Po
#	source='$(LOCAL_RESOURCE_FOLDER)/pof_ins_block.c' object='pof_ins_block.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o pof_ins_block.obj `if test -f '$(LOCAL_RESOURCE_FOLDER)/pof_ins_block.c'; then $(CYGPATH_W) '$(LOCAL_RESOURCE_FOLDER)/pof_ins_block.c'; else $(CYGPATH_W) '$(srcdir)/$(LOCAL_RESOURCE_FOLDER)/pof_ins_block.c'; fi`

pof_port.o: $(LOCAL_RESOURCE_FOLDER)/pof_port.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT pof_port.o -MD -MP -MF $(DEPDIR)/pof_port.Tpo -c -o pof_port.o `test -f '$(LOCAL_RESOURCE_FOLDER)/pof_port.c' || echo '$(srcdir)/'`$(LOCAL_RESOURCE_FOLDER)/pof_port.c
	$(am__mv) $(DEPDIR)/pof_port.Tpo $(DEPDIR)/pof_port.Po
#	source='$(LOCAL_RESOURCE_FOLDER)/pof_port.c' object='pof_port.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o pof_port.o `test -f '$(LOCAL_RESOURCE_FOLDER)/pof_port.c' || echo '$(srcdir)/'`$(LOCAL_RESOURCE_FOLDER)/pof_port.c

pof_port.obj: $(LOCAL_RESOURCE_FOLDER)/pof_port.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT pof_port.obj -MD -MP -MF $(DEPDIR)/pof_port.Tpo -c -o pof_port.obj `if test -f '$(LOCAL_RESOURCE_FOLDER)/pof_port.c'; then $(CYGPATH_W) '$(LOCAL_RESOURCE_FOLDER)/pof_port.c'; else $(CYGPATH_W) '$(srcdir)/$(LOCAL_RESOURCE_FOLDER)/pof_port.c'; fi`
	$(am__mv) $(DEPDIR)/pof_port.Tpo $(DEPDIR)/pof_port.Po
#	source='$(LOCAL_RESOURCE_FOLDER)/pof_port.c' object='pof_port.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o pof_port.obj `if test -f '$(LOCAL_RESOURCE_FOLDER)/pof_port.c'; then $(CYGPATH_W) '$(LOCAL_RESOURCE_FOLDER)/pof_port.c'; else $(CYGPATH_W) '$(srcdir)/$(LOCAL_RESOURCE_FOLDER)/pof_port.c'; fi`

pof_config.o: $(SWITCH_CONTROL_FOLDER)/pof_config.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT pof_config.o -MD -MP -MF $(DEPDIR)/pof_config.Tpo -c -o pof_config.o `test -f '$(SWITCH_CONTROL_FOLDER)/pof_config.c' || echo '$(srcdir)/'`$(SWITCH_CONTROL_FOLDER)/pof_config.c
	$(am__mv) $(DEPDIR)/pof_config.Tpo $(DEPDIR)/pof_config.Po
#	source='$(SWITCH_CONTROL_FOLDER)/pof_config.c' object='pof_config.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o pof_config.o `test -f '$(SWITCH_CONTROL_FOLDER)/pof_config.c' || echo '$(srcdir)/'`$(SWITCH_CONTROL_FOLDER)/pof_config.c

pof_config.obj: $(SWITCH_CONTROL_FOLDER)/pof_config.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT pof_config.obj -MD -MP -MF $(DEPDIR)/pof_config.Tpo -c -o pof_config.obj `if test -f '$(SWITCH_CONTROL_FOLDER)/pof_config.c'; then $(CYGPATH_W) '$(SWITCH_CONTROL_FOLDER)/pof_config.c'; else $(CYGPATH_W) '$(srcdir)/$(SWITCH_CONTROL_FOLDER)/pof_config.c'; fi`
	$(am__mv) $(DEPDIR)/pof_config.Tpo $(DEPDIR)/pof_config.Po
#	source='$(SWITCH_CONTROL_FOLDER)/pof_config.c' object='pof_config.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o pof_config.obj `if test -f '$(SWITCH_CONTROL_FOLDER)/pof_config.c'; then $(CYGPATH_W) '$(SWITCH_CONTROL_FOLDER)/pof_config.c'; else $(CYGPATH_W) '$(srcdir)/$(SWITCH_CONTROL_FOLDER)/pof_config.c'; fi`

pof_encap.o: $(SWITCH_CONTROL_FOLDER)/pof_encap.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT pof_encap.o -MD -MP -MF $(DEPDIR)/pof_encap.Tpo -c -o pof_encap.o `test -f '$(SWITCH_CONTROL_FOLDER)/pof_encap.c' || echo '$(srcdir)/'`$(SWITCH_CONTROL_FOLDER)/pof_encap.c
	$(am__mv) $(DEPDIR)/pof_encap.Tpo $(DEPDIR)/pof_encap.Po
#	source='$(SWITCH_CONTROL_FOLDER)/pof_encap.c' object='pof_encap.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o pof_encap.o `test -f '$(SWITCH_CONTROL_FOLDER)/pof_encap.c' || echo '$(srcdir)/'`$(SWITCH_CONTROL_FOLDER)/pof_encap.c

pof_encap.obj: $(SWITCH_CONTROL_FOLDER)/pof_encap.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT pof_encap.obj -MD -MP -MF $(DEPDIR)/pof_encap.Tpo -c -o pof_encap.obj `if test -f '$(SWITCH_CONTROL_FOLDER)/pof_encap.c'; then $(CYGPATH_W) '$(SWITCH_CONTROL_FOLDER)/pof_encap.c'; else $(CYGPATH_W) '$(srcdir)/$(SWITCH_CONTROL_FOLDER)/pof_encap.c'; fi`
	$(am__mv) $(DEPDIR)/pof_encap.Tpo $(DEPDIR)/pof_encap.Po
#	source='$(SWITCH_CONTROL_FOLDER)/pof_encap.c' object='pof_encap.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o pof_encap.obj `if test -f '$(SWITCH_CONTROL_FOLDER)/pof_encap.c'; then $(CYGPATH_W) '$(SWITCH_CONTROL_FOLDER)/pof_encap.c'; else $(CYGPATH_W) '$(srcdir)/$(SWITCH_CONTROL_FOLDER)/pof_encap.c'; fi`

pof_parse.o: $(SWITCH_CONTROL_FOLDER)/pof_parse.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT pof_parse.o -MD -MP -MF $(DEPDIR)/pof_parse.Tpo -c -o pof_parse.o `test -f '$(SWITCH_CONTROL_FOLDER)/pof_parse.c' || echo '$(srcdir)/'`$(SWITCH_CONTROL_FOLDER)/pof_parse.c
	$(am__mv) $(DEPDIR)/pof_parse.Tpo $(DEPDIR)/pof_parse.Po
#	source='$(SWITCH_CONTROL_FOLDER)/pof_parse.c' object='pof_parse.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o pof_parse.o `test -f '$(SWITCH_CONTROL_FOLDER)/pof_parse.c' || echo '$(srcdir)/'`$(SWITCH_CONTROL_FOLDER)/pof_parse.c

pof_parse.obj: $(SWITCH_CONTROL_FOLDER)/pof_parse.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT pof_parse.obj -MD -MP -MF $(DEPDIR)/pof_parse.Tpo -c -o pof_parse.obj `if test -f '$(SWITCH_CONTROL_FOLDER)/pof_parse.c'; then $(CYGPATH_W) '$(SWITCH_CONTROL_FOLDER)/pof_parse.c'; else $(CYGPATH_W) '$(srcdir)/$(SWITCH_CONTROL_FOLDER)/pof_parse.c'; fi`
	$(am__mv) $(DEPDIR)/pof_parse.Tpo $(DEPDIR)/pof_parse.Po
#	source='$(SWITCH_CONTROL_FOLDER)/pof_parse.c' object='pof_parse.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o pof_parse.obj `if test -f '$(SWITCH_CONTROL_FOLDER)/pof_parse.c'; then $(CYGPATH_W) '$(SWITCH_CONTROL_FOLDER)/pof_parse.c'; else $(CYGPATH_W) '$(srcdir)/$(SWITCH_CONTROL_FOLDER)/pof_parse.c'; fi`

pof_switch_listen.o: $(SWITCH_CONTROL_FOLDER)/pof_switch_listen.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT pof_switch_listen.o -MD -MP -MF $(DEPDIR)/pof_switch_listen.Tpo -c -o pof_switch_listen.o `test -f '$(SWITCH_CONTROL_FOLDER)/pof_switch_listen.c' || echo '$(srcdir)/'`$(SWITCH_CONTROL_FOLDER)/pof_switch_listen.c
	$(am__mv) $(DEPDIR)/pof_switch_listen.Tpo $(DEPDIR)/pof_switch_listen.Po
#	source='$(SWITCH_CONTROL_FOLDER)/pof_switch_listen.c' object='pof_switch_listen.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o pof_switch_listen.o `test -f '$(SWITCH_CONTROL_FOLDER)/pof_switch_listen.c' || echo '$(srcdir)/'`$(SWITCH_CONTROL_FOLDER)/pof_switch_listen.c

pof_switch_listen.obj: $(SWITCH_CONTROL_FOLDER)/pof_switch_listen.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT pof_switch_listen.obj -MD -MP -MF $(DEPDIR)/pof_switch_listen.Tpo -c -o pof_switch_listen.obj `if test -f '$(SWITCH_CONTROL_FOLDER)/pof_switch_listen.c'; then $(CYGPATH_W) '$(SWITCH_CONTROL_FOLDER)/pof_switch_listen.c'; else $(CYGPATH_W) '$(srcdir)/$(SWITCH_CONTROL_FOLDER)/pof_switch_listen.c'; fi`
	$(am__mv) $(DEPDIR)/pof_switch_listen.Tpo $(DEPDIR)/pof_switch_listen.Po
#	source='$(SWITCH_CONTROL_FOLDER)/pof_switch_listen.c' object='pof_switch_listen.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o pof_switch_listen.obj `if test -f '$(SWITCH_CONTROL_FOLDER)/pof_switch_listen.c'; then $(CYGPATH_W) '$(SWITCH_CONTROL_FOLDER)/pof_switch_listen.c'; else $(CYGPATH_W) '$(srcdir)/$(SWITCH_CONTROL_FOLDER)/pof_switch_listen.c'; fi`

pof_switch.o: $(SWITCH_CONTROL_FOLDER)/pof_switch.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT pof_switch.o -MD -MP -MF $(DEPDIR)/pof_switch.Tpo -c -o pof_switch.o `test -f '$(SWITCH_CONTROL_FOLDER)/pof_switch.c' || echo '$(srcdir)/'`$(SWITCH_CONTROL_FOLDER)/pof_switch.c
	$(am__mv) $(DEPDIR)/pof_switch.Tpo $(DEPDIR)/pof_switch.Po
#	source='$(SWITCH_CONTROL_FOLDER)/pof_switch.c' object='pof_switch.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o pof_switch.o `test -f '$(SWITCH_CONTROL_FOLDER)/pof_switch.c' || echo '$(srcdir)/'`$(SWITCH_CONTROL_FOLDER)/pof_switch.c

pof_switch.obj: $(SWITCH_CONTROL_FOLDER)/pof_switch.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT pof_switch.obj -MD -MP -MF $(DEPDIR)/pof_switch.Tpo -c -o pof_switch.obj `if test -f '$(SWITCH_CONTROL_FOLDER)/pof_switch.c'; then $(CYGPATH_W) '$(SWITCH_CONTROL_FOLDER)/pof_switch.c'; else $(CYGPATH_W) '$(srcdir)/$(SWITCH_CONTROL_FOLDER)/pof_switch.c'; fi`
	$(am__mv) $(DEPDIR)/pof_switch.Tpo $(DEPDIR)/pof_switch.Po
#	source='$(SWITCH_CONTROL_FOLDER)/pof_switch.c' object='pof_switch.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o pof_switch.obj `if test -f '$(SWITCH_CONTROL_FOLDER)/pof_switch.c'; then $(CYGPATH_W) '$(SWITCH_CONTROL_FOLDER)/pof_switch.c'; else $(CYGPATH_W) '$(srcdir)/$(SWITCH_CONTROL_FOLDER)/pof_switch.c'; fi`

ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	mkid -fID $$unique
tags: TAGS

TAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	set x; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS)  $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: CTAGS
CTAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	list='$(SOURCES) $(HEADERS)  $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags

distdir: $(DISTFILES)
	$(am__remove_distdir)
	test -d "$(distdir)" || mkdir "$(distdir)"
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
	-test -n "$(am__skip_mode_fix)" \
	|| find "$(distdir)" -type d ! -perm -755 \
		-exec chmod u+rwx,go+rx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r "$(distdir)"
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | BZIP2=$${BZIP2--9} bzip2 -c >$(distdir).tar.bz2
	$(am__remove_distdir)

dist-lzip: distdir
	tardir=$(distdir) && $(am__tar) | lzip -c $${LZIP_OPT--9} >$(distdir).tar.lz
	$(am__remove_distdir)

dist-lzma: distdir
	tardir=$(distdir) && $(am__tar) | lzma -9 -c >$(distdir).tar.lzma
	$(am__remove_distdir)

dist-xz: distdir
	tardir=$(distdir) && $(am__tar) | XZ_OPT=$${XZ_OPT--e} xz -c >$(distdir).tar.xz
	$(am__remove_distdir)

dist-tarZ: distdir
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__remove_distdir)

dist-shar: distdir
	shar $(distdir) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).shar.gz
	$(am__remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__remove_distdir)

dist dist-all: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bzip2 -dc $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.lzma*) \
	  lzma -dc $(distdir).tar.lzma | $(am__untar) ;;\
	*.tar.lz*) \
	  lzip -dc $(distdir).tar.lz | $(am__untar) ;;\
	*.tar.xz*) \
	  xz -dc $(distdir).tar.xz | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	esac
	chmod -R a-w $(distdir); chmod a+w $(distdir)
	mkdir $(distdir)/_build
	mkdir $(distdir)/_inst
	chmod a-w $(distdir)
	test -d $(distdir)/_build || exit 0; \
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && am__cwd=`pwd` \
	  && $(am__cd) $(distdir)/_build \
	  && ../configure --srcdir=.. --prefix="$$dc_install_base" \
	    $(AM_DISTCHECK_CONFIGURE_FLAGS) \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck \
	  && cd "$$am__cwd" \
	  || exit 1
	$(am__remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@test -n '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: trying to run $@ with an empty' \
	       '$$(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	$(am__cd) '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: cannot chdir into $(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	test `$(am__distuninstallcheck_listfiles) | wc -l` -eq 0 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: check-am
all-am: Makefile $(PROGRAMS)
installdirs:
	for dir in "$(DESTDIR)$(bindir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	if test -z '$(STRIP)'; then \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	      install; \
	else \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	    "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'" install; \
	fi
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-am

clean-am: clean-binPROGRAMS clean-generic clean-local mostlyclean-am

distclean: distclean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-tags

dvi: dvi-am

dvi-am:

html: html-am

html-am:

info: info-am

info-am:

install-data-am: install-data-local

install-dvi: install-dvi-am

install-dvi-am:

install-exec-am: install-binPROGRAMS

install-html: install-html-am

install-html-am:

install-info: install-info-am

install-info-am:

install-man:

install-pdf: install-pdf-am

install-pdf-am:

install-ps: install-ps-am

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

uninstall-am: uninstall-binPROGRAMS uninstall-local

.MAKE: install-am install-strip

.PHONY: CTAGS GTAGS all all-am am--refresh check check-am clean \
	clean-binPROGRAMS clean-generic clean-local ctags dist \
	dist-all dist-bzip2 dist-gzip dist-lzip dist-lzma dist-shar \
	dist-tarZ dist-xz dist-zip distcheck distclean \
	distclean-compile distclean-generic distclean-tags \
	distcleancheck distdir distuninstallcheck dvi dvi-am html \
	html-am info info-am install install-am install-binPROGRAMS \
	install-data install-data-am install-data-local install-dvi \
	install-dvi-am install-exec install-exec-am install-html \
	install-html-am install-info install-info-am install-man \
	install-pdf install-pdf-am install-ps install-ps-am \
	install-strip installcheck installcheck-am installdirs \
	maintainer-clean maintainer-clean-generic mostlyclean \
	mostlyclean-compile mostlyclean-generic pdf pdf-am ps ps-am \
	tags uninstall uninstall-am uninstall-binPROGRAMS \
	uninstall-local


install-data-local:
	mkdir -p $(INSTALL_DATA_PATH)
	mkdir -p $(LOG_FILE_PATH)
	cp $(top_srcdir)/$(POFCONFIG_FILE) $(INSTALL_DATA_PATH)
	cp $(top_srcdir)/$(bin_PROGRAMS) $(SBIN_PATH)
uninstall-local:
	rm -rf $(INSTALL_DATA_PATH)
	rm -f $(SBIN_PATH)/$(bin_PROGRAMS) $(LOG_FILE_PATH)/pofswitch.log
clean-local:
	rm -f cscope* tags

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
